### ISSUE TITLE
Release dmg missing two files

### ISSUE THREAD

**Issue by emendelson** [miyako/console-rsvg-convert#4]
Hello,

Testing under Mojave, the executable in the .dmg will not run because two files are missing:

libiconv.2.dylib
libz.1.dylib

I found copies of these files in other projects and added them to the folder with rsvg-convert, and was able to use the executable. Could they be added to the distribution?

**Comment by miyako** [comment]
probably an `install_name_tool` misconfiguration, the dylib loader looking at `usr/local*` instead of `@loader/path`. 

will look into it.

**Comment by miyako** [comment]
updated 

https://github.com/miyako/console-rsvg-convert/releases/tag/2.1.2

**Comment by emendelson** [comment]
Fixed. Thank you!
